meta_title: "Planisfer - Roadtrips in Europe"
meta_description: "You want to do a roadtrip in Europe? Find the best way to discover new regions"
meta_image: "background.jpg" # Une image dans votre dossier app/assets/images/


twitter_account: "@NicolasFerrary" # indispensable pour les Twitter Cards
