meta_title: "Planisfer - Explore the world your own way"
meta_description: "Prepare and book fully costomized trips"
meta_image: "planisfer_meta_photo.jpg" # Une image dans votre dossier app/assets/images/


twitter_account: "@NicolasFerrary" # indispensable pour les Twitter Cards
